from datetime import date

# 15 categories × 16 angles = 240 unique topics before cycling
CATEGORIES = [
    {
        "name": "SIP aur Mutual Funds",
        "angles": [
            "SIP kya hota hai aur aaj se shuru kaise karein — complete beginner guide",
            "500 rupay mahine ki SIP se 10 saal mein kitna banega — real calculation",
            "ELSS kya hai aur tax kaise bachata hai — Section 80C guide",
            "Index Funds vs Active Funds — kaunsa better hai India mein",
            "Mutual Fund direct plan vs regular plan — kitna farak padta hai",
            "SIP mein market crash aaye toh kya karein — step by step guide",
            "Parabolic growth: SIP se pehle 10 saal mein slow growth kyun hoti hai",
            "Lumpsum vs SIP — dono ka sahi use case kab hota hai",
            "Flexi-cap vs Large-cap funds — naye investors ke liye kaunsa sahi",
            "NAV kya hota hai aur kya isko dekh ke fund choose karein",
            "SIP topup strategy: har saal SIP amount kaise badhayein",
            "Best mutual funds India 2024 — 5 saal ka track record dekhein",
            "Sectoral funds mein invest karna chahiye ya nahi — honest review",
            "KYC kaise complete karein aur SIP shuru karein — 10 minute mein",
            "SWP (Systematic Withdrawal Plan) kya hai aur retirement mein kaise use karein",
            "Dividend vs Growth option — kaunsa choose karein aur kyun",
        ],
    },
    {
        "name": "Stock Market Basics",
        "angles": [
            "Stock market mein invest karna shuru kaise karein — zero se hero guide",
            "Demat account kya hota hai aur kaise open karein free mein",
            "P/E ratio kya hai aur kaise stock select karein",
            "Blue-chip stocks kya hote hain aur kyun safe maane jaate hain",
            "Dividend investing kya hai — passive income stocks India",
            "Stop loss kya hai aur kaise set karein — beginners guide",
            "Nifty 50 mein directly invest kaise karein bina fund manager ke",
            "IPO mein apply karna chahiye ya nahi — sach kya hai",
            "F&O trading kya hai aur beginners ko kyun avoid karna chahiye",
            "Fundamental vs Technical analysis — kaunsa better hai long term ke liye",
            "Market cap kya hota hai — large, mid, small cap ka farak",
            "5 Indian companies jinke stocks 10 saal se consistently badhte hain",
            "Dollar cost averaging kya hai — stock market mein apply kaise karein",
            "Portfolio diversification — kitne stocks rakhne chahiye",
            "Bonus shares aur stock split — kya hota hai aur investor ko kya fayda",
            "Quarterly results kaise padhein — simple guide for beginners",
        ],
    },
    {
        "name": "Tax Saving",
        "angles": [
            "Section 80C mein kya kya aata hai — poora guide ek video mein",
            "HRA exemption kaise milti hai — rent pe tax kaise bachayein",
            "Old tax regime vs new tax regime — 2024 mein kaunsa better hai",
            "Form 16 kya hota hai aur ITR kaise file karein khud se",
            "NPS se 50,000 extra tax deduction kaise milti hai — Section 80CCD",
            "Health insurance premium se tax kaise bachayein — Section 80D",
            "Home loan ke interest pe kitna tax bachta hai — Section 24",
            "Tax harvesting kya hai — mutual fund gains par tax kaise reduce karein",
            "Capital gains tax kya hota hai — STCG vs LTCG explained",
            "Freelancers ke liye tax saving tips — business expenses kaise claim karein",
            "5 common mistakes jo log ITR file karte waqt karte hain",
            "Tax exempt investments — PPF, SSY, Sukanya Samriddhi complete guide",
            "Advance tax kya hai aur kab bharna padta hai",
            "TDS kya hota hai aur refund kaise le — simple explanation",
            "Gift tax — family ko paise dene par tax lagta hai ya nahi",
            "80G donation deduction — NGO ko daan deke tax kaise bachayein",
        ],
    },
    {
        "name": "Credit Cards aur Loans",
        "angles": [
            "Credit card use karna chahiye ya nahi — honest pros and cons",
            "Credit score kya hota hai aur 750+ score kaise banayein",
            "Credit card ka minimum payment trap — 10,000 ka loan 50,000 kaise banta hai",
            "Home loan EMI ya rent — 2024 mein kaunsa smart choice hai",
            "Personal loan interest rate kaise kam karein — negotiation tips",
            "CIBIL score kaise check karein free mein aur improve karein",
            "Credit card rewards kaise maximize karein — best strategy",
            "Loan prepayment vs investment — kaunsa pehle karein",
            "Education loan lena chahiye ya nahi — complete analysis",
            "5 credit card mistakes jo India mein bahut log karte hain",
            "EMI no cost ka sach — kya actually free hota hai",
            "Balance transfer kya hai aur credit card debt kaise khatam karein",
            "Overdraft facility kya hoti hai — current account guide",
            "Car loan vs cash purchase — konsa financially smart hai",
            "Credit card churning kya hai — free flights aur cashback strategy",
            "Loan against FD — emergency mein best option kyun hai",
        ],
    },
    {
        "name": "Emergency Fund aur Saving",
        "angles": [
            "Emergency fund kya hota hai aur kitna hona chahiye — full guide",
            "Zero se emergency fund kaise banayein — 6 month ka plan",
            "50-30-20 rule kya hai — salary kaise divide karein",
            "Salary aate hi pehle kya karein — pay yourself first rule",
            "Paisa bachane ke liye 7 daily habits jo actually kaam karti hain",
            "Inflation kya hai aur aapki savings ko kaise kha jaati hai",
            "Liquid fund kya hai — emergency fund ke liye FD se better kyun",
            "Impulse buying rokne ke 5 psychological tricks",
            "Monthly budget kaise banayein — Google Sheets template",
            "Subscriptions audit — kitna paisa waste ho raha hai monthly",
            "Gold savings account vs physical gold — kaunsa better hai",
            "Recurring deposit vs SIP — small savings ke liye kaunsa",
            "Paisa save karne ke liye 30 day challenge — try it",
            "Bank mein idle paise mat rakhein — better alternatives",
            "Savings account interest rate maximize kaise karein — best banks 2024",
            "Zero-based budgeting kya hai aur kaise implement karein",
        ],
    },
    {
        "name": "Insurance",
        "angles": [
            "Term life insurance kya hai aur kitna cover lena chahiye",
            "Health insurance lene ka sahi time — age aur premium ka relation",
            "ULIP vs term insurance + mutual fund — kaunsa better hai",
            "LIC policy surrender karna chahiye ya nahi — honest answer",
            "Floater vs individual health insurance — family ke liye kaunsa",
            "Cashless health insurance claim kaise karein — step by step",
            "Critical illness cover kya hota hai aur kab lena chahiye",
            "Vehicle insurance third party vs comprehensive — kaunsa lein",
            "Insurance agent ke tips pe blindly trust mat karein — ye questions poochein",
            "Endowment policy ka sach — returns actually kitne hote hain",
            "Term insurance riders kya hote hain — accidental death, disability",
            "Group health insurance vs personal — dono rakhein ya ek",
            "Insurance claim reject hone ke 5 common reasons",
            "Super top-up health insurance kya hai — affordable coverage ka secret",
            "Corona Kavach vs regular health insurance — kya farak hai",
            "Insurance portability — better plan pe switch kaise karein",
        ],
    },
    {
        "name": "Retirement Planning",
        "angles": [
            "PPF account kya hai aur 15 saal mein kaise grow karta hai",
            "NPS (National Pension System) complete guide — kaise invest karein",
            "30 saal ki umra se retire hone ka plan — FIRE movement India",
            "EPF (Provident Fund) se paisa kab nikalein aur kab nahi",
            "Retirement ke liye kitna paisa chahiye — calculation",
            "Annuity kya hoti hai — retirement income plan",
            "SCSS (Senior Citizen Savings Scheme) — parents ke liye best option",
            "Pension vs corpus — which retirement strategy is better",
            "VPF kya hai — EPF se extra contribution ka faida",
            "Retirement planning mein inflation ko kaise account karein",
            "EPF vs PPF vs NPS — teen options ka comparison",
            "Part-time work after retirement — financial aur mental benefits",
            "Retirement mein healthcare costs ke liye kitna save karein",
            "Systematic Withdrawal Plan — retirement mein monthly income kaise lein",
            "Early retirement ke liye corpus — 40 saal mein retire hona",
            "Will aur nominee — retirement se pehle ye zarur karein",
        ],
    },
    {
        "name": "Real Estate",
        "angles": [
            "Ghar kharidna chahiye ya kiraye mein rehna — 2024 ka honest analysis",
            "Home loan ke liye apply karne se pehle ye 7 cheezein check karein",
            "Builder floor vs society apartment vs independent house — pros cons",
            "RERA kya hai — property kharidne se pehle ye zarur check karein",
            "Property registration process — stamp duty aur registration charges",
            "REITs kya hote hain — bina property kharide real estate mein invest",
            "Ghar bechne ka sahi time — property market cycle samjhein",
            "Home loan balance transfer kab karein aur kitna bacha sakte hain",
            "Under-construction vs ready-to-move property — kaunsa safe hai",
            "Property ki valuation kaise karein — market rate kaise pata karein",
            "Joint home loan ke fayde — wife ke naam pe loan kyun lein",
            "NRI property investment India mein — rules aur tax implications",
            "Rental yield kya hai — investment property khareedne se pehle calculate karein",
            "Proptech apps India — real estate research ke liye best tools",
            "Property mein black money — risks aur consequences",
            "Agricultural land mein invest karna chahiye ya nahi",
        ],
    },
    {
        "name": "Gold aur Alternatives",
        "angles": [
            "Sovereign Gold Bond kya hai — physical gold se better kyun",
            "Digital gold vs physical gold vs gold ETF — sabka comparison",
            "Gold kitna rakhna chahiye portfolio mein — expert opinion",
            "Gold ki price kiski wajah se badhti hai — factors explained",
            "Gold ETF kaise kharidein — step by step guide",
            "Chandi mein invest karna chahiye — silver investment analysis",
            "Gold loan kya hota hai — emergency mein best option",
            "Jewelry gold investment hai ya expense — honest answer",
            "International gold vs Indian gold price — farak kyun hota hai",
            "Hallmark gold kya hota hai — aur kyun zaroori hai kharidne se pehle check karna",
            "Gold mein long term returns — 20 saal ka data dekhtein hain",
            "Gold SIP kya hai — monthly gold kharidne ka smart way",
            "Commodity market kya hai — gold trading vs gold investing",
            "Gold vs fixed deposit — inflation adjust returns comparison",
            "RBI retail direct kya hai — government bonds directly kaise kharidein",
            "Cryptocurrency vs gold — store of value comparison",
        ],
    },
    {
        "name": "Digital Payments aur Banking",
        "angles": [
            "UPI fraud se kaise bachein — 10 important safety rules",
            "Zero balance account kaunsa bank best offer karta hai 2024 mein",
            "FD rates comparison — konsa bank de raha hai sabse zyada",
            "Savings account vs current account — aapke liye kaunsa sahi hai",
            "Internet banking safely use karne ke 8 golden rules",
            "Credit card vs debit card — kaunsa use karein aur kab",
            "UPI apps comparison — GPay vs PhonePe vs Paytm — kaunsa best hai",
            "Bank locker lena chahiye ya nahi — cost benefit analysis",
            "Nominee update karna kaise zaruri hai — bank accounts ke liye",
            "Digital wallet vs bank account — kya farak hai",
            "NACH mandate kya hota hai — auto-debit kaise kaam karta hai",
            "Bank FD prematurely todne ka nuksan — kab todein kab nahi",
            "Online fraud hone par kya karein — immediate steps",
            "RBI floating rate savings bond — FD se better option",
            "Banking ombudsman — bank se problem hai toh kahan complain karein",
            "Overdraft protection vs personal loan — konsa choose karein",
        ],
    },
    {
        "name": "Passive Income",
        "angles": [
            "Passive income ke 7 realistic sources Indians ke liye",
            "Dividend income — stock market se monthly paise kaise aayein",
            "Rental income — property se passive income ki complete guide",
            "Blogging se paise kaise kamayein — 2024 mein realistic expectations",
            "YouTube se paise — monetization threshold aur reality check",
            "Freelancing side income kaise shuru karein — platforms aur tips",
            "Print on demand — bina investment ke online business",
            "Fixed deposits aur bonds se regular income — ladder strategy",
            "REITs se quarterly dividend income kaise milti hai",
            "Affiliate marketing kya hai — genuine passive income ya myth",
            "App development — ek app se lifetime passive income",
            "Online courses banao aur bechho — knowledge monetization",
            "Peer to peer lending — high returns ka sach aur risk",
            "Domain flipping — domain names se paise kaise kamayein",
            "Stock options aur dividends combined strategy",
            "Dropshipping business India mein — sach kitna profitable hai",
        ],
    },
    {
        "name": "Common Money Mistakes",
        "angles": [
            "20s mein ki jaane wali 5 biggest financial mistakes",
            "Inflation ka pata nahi — FD mein sab paise rakhne ka nuksaan",
            "Insurance investment ki tarah lena — endowment trap",
            "EMI culture — kab EMI theek hai aur kab nuksan hai",
            "Investing without emergency fund — sabse badi galati",
            "Social media dekh ke invest karna — finfluencer trap",
            "Paisa late invest karna — har saal ki delay kitni mehengi padti hai",
            "Diversification na karna — sab ande ek basket mein",
            "Tax nahi bharna — penalties aur consequences",
            "Joint account risks — beware of shared finances",
            "Crypto mein FOMO invest — losses ka real data",
            "Car loan pe luxury car lena — lifestyle inflation trap",
            "Medical insurance na rakhna — ek bimari se savings wipe out",
            "Will na banana — legal complications for family",
            "Penny stocks aur multi-bagger traps — scam kaise pehchaaein",
            "Churning investments — baar baar switch karne se returns kaise kam hote hain",
        ],
    },
    {
        "name": "Startup aur Business Finance",
        "angles": [
            "Business shuru karne se pehle ye 5 financial steps zarur lein",
            "GST registration kab karein aur kaise — small business guide",
            "Business account personal account se alag kyun rakhein",
            "Startup funding options India — bootstrapping vs investors",
            "Mudra loan kya hai — 10 lakh tak bina guarantee ke loan",
            "Business credit card ke fayde — cash flow management",
            "Freelancer ITR filing — how to show income and expenses",
            "Working capital kya hai aur kaise manage karein",
            "Restaurant business financial model — realistic margins",
            "E-commerce business tax compliance guide India",
            "Angel investor vs VC — startup funding differences",
            "Business insurance — kab zaruri hai aur kaunsa lein",
            "Partner ke saath business — legal agreement kyun zaroori hai",
            "Invoice financing kya hai — B2B business cash flow solution",
            "MSME registration ke fayde — government schemes aur loans",
            "Profitability vs cash flow — dono alag kyun hote hain",
        ],
    },
    {
        "name": "Personal Finance Psychology",
        "angles": [
            "Loss aversion kya hai — aur investment decisions kaise kharab karta hai",
            "Lifestyle inflation — salary badhte hi kharch kyun badhte hain",
            "Financial goals set karne ka sahi tarika — SMART goals",
            "Money mindset — rich log paise ke baare mein alag kyun sochte hain",
            "Delayed gratification — marshmallow test aur wealth building",
            "Comparison trap — dusron ko dekh ke financial decisions mat lena",
            "Fear of investing — psychological barriers aur unhe kaise todein",
            "Sunk cost fallacy — bad investment mein stuck kyun rehte hain",
            "Mental accounting kya hai — entertainment budget vs investment",
            "Dopamine aur online shopping — impulse buy se kaise bachein",
            "Financial stress management — paise ki tension kaise kaam karein",
            "Money conversations — partner aur family ke saath finance kaise discuss karein",
            "Confirmation bias — sirf wahi dekhna jo hum dekhna chahte hain",
            "Recency bias — recent market crash se overreact karna",
            "Anchoring bias — first number ka undue influence",
            "Financial journaling — paise track karne ka powerful habit",
        ],
    },
    {
        "name": "India-Specific Finance",
        "angles": [
            "PM Jan Dhan scheme — features aur benefits jo aap nahi jaante",
            "Aadhaar linked bank account — benefits aur security",
            "PM Kisan nidhi — farmers ke liye government scheme",
            "Atal Pension Yojana — low income ke liye retirement plan",
            "Sukanya Samriddhi Yojana — beti ke liye best investment",
            "PM Mudra Yojana — business loan bina guarantee ke",
            "Post office savings schemes — hidden gems in India",
            "Kisan Vikas Patra — double money scheme ki reality",
            "NSC vs PPF — post office vs bank savings",
            "Senior citizen tax benefits — 60+ ke liye special provisions",
            "NRI ke liye NRE vs NRO account — kaunsa sahi hai",
            "PMVVY — Pradhan Mantri Vaya Vandana Yojana for senior citizens",
            "Atmanirbhar Bharat schemes — MSMEs aur small businesses ke liye",
            "State government schemes — apne state ki finance yojnaayein",
            "PM Fasal Bima Yojana — agricultural insurance guide",
            "One Nation One Ration Card — benefits and how to use",
        ],
    },
]


def get_todays_topic() -> dict:
    all_angles = [
        {"category": cat["name"], "angle": angle}
        for cat in CATEGORIES
        for angle in cat["angles"]
    ]
    idx = date.today().timetuple().tm_yday % len(all_angles)
    return all_angles[idx]
