"""
Curated AI tools list for Mahayukti AI channel.
300+ tools — no repeats for 10+ months of daily posts.
"""

TOOLS = [
    # ── Productivity & Writing ─────────────────────────────────────────────
    {"name": "ChatGPT",           "category": "Productivity",     "maker": "OpenAI",        "pricing": "Free + $20/mo Plus",             "india_available": True,  "india_note": "Works in India; needs card for paid plan"},
    {"name": "Claude",            "category": "Productivity",     "maker": "Anthropic",     "pricing": "Free + $20/mo Pro",              "india_available": True,  "india_note": "Fully available; UPI not accepted for paid"},
    {"name": "Gemini",            "category": "Productivity",     "maker": "Google",        "pricing": "Free + $20/mo Advanced",         "india_available": True,  "india_note": "Best India integration; works with Google Workspace"},
    {"name": "Microsoft Copilot", "category": "Productivity",     "maker": "Microsoft",     "pricing": "Free; $30/mo for 365 Copilot",   "india_available": True,  "india_note": "Integrated into Windows 11 and Office 365"},
    {"name": "Perplexity AI",     "category": "Search",           "maker": "Perplexity",    "pricing": "Free + $20/mo Pro",              "india_available": True,  "india_note": "Works in India; excellent for research"},
    {"name": "Notion AI",         "category": "Productivity",     "maker": "Notion",        "pricing": "$10/mo add-on",                  "india_available": True,  "india_note": "Popular among Indian startups and students"},
    {"name": "Jasper AI",         "category": "Writing",          "maker": "Jasper",        "pricing": "From $49/mo",                    "india_available": True,  "india_note": "Best for marketing teams; pricey for individuals"},
    {"name": "Copy.ai",           "category": "Writing",          "maker": "Copy.ai",       "pricing": "Free + $49/mo",                  "india_available": True,  "india_note": "Great free tier; good for short-form content"},
    {"name": "Writesonic",        "category": "Writing",          "maker": "Writesonic",    "pricing": "Free + from $16/mo",             "india_available": True,  "india_note": "Has India-specific pricing; good value"},
    {"name": "Grammarly AI",      "category": "Writing",          "maker": "Grammarly",     "pricing": "Free + $12/mo Premium",          "india_available": True,  "india_note": "Very popular in India for English writing"},

    # ── Image Generation ──────────────────────────────────────────────────
    {"name": "Midjourney",        "category": "Image AI",         "maker": "Midjourney",    "pricing": "From $10/mo",                    "india_available": True,  "india_note": "Via Discord; needs card; worth every rupee"},
    {"name": "DALL-E 3",          "category": "Image AI",         "maker": "OpenAI",        "pricing": "Included in ChatGPT Plus",       "india_available": True,  "india_note": "Best quality; bundled with ChatGPT Plus"},
    {"name": "Adobe Firefly",     "category": "Image AI",         "maker": "Adobe",         "pricing": "25 credits/mo free",             "india_available": True,  "india_note": "Commercially safe images; great for designers"},
    {"name": "Canva AI",          "category": "Image AI",         "maker": "Canva",         "pricing": "Free + ₹3999/yr Pro",            "india_available": True,  "india_note": "India pricing in INR; most popular design tool"},
    {"name": "Leonardo AI",       "category": "Image AI",         "maker": "Leonardo",      "pricing": "Free + from $12/mo",             "india_available": True,  "india_note": "Best free tier for image generation"},
    {"name": "Ideogram",          "category": "Image AI",         "maker": "Ideogram",      "pricing": "Free + from $8/mo",              "india_available": True,  "india_note": "Best for text-in-image generation"},
    {"name": "Stable Diffusion",  "category": "Image AI",         "maker": "Stability AI",  "pricing": "Free (open source)",             "india_available": True,  "india_note": "Run locally for free; needs decent GPU"},
    {"name": "Flux AI",           "category": "Image AI",         "maker": "Black Forest Labs","pricing": "Free via Replicate",           "india_available": True,  "india_note": "Beats Midjourney on realism; free via Replicate"},
    {"name": "Imagen 3",          "category": "Image AI",         "maker": "Google",        "pricing": "Via Gemini Advanced",            "india_available": True,  "india_note": "Google's best image AI; needs Gemini subscription"},
    {"name": "Playground AI",     "category": "Image AI",         "maker": "Playground",    "pricing": "Free + from $15/mo",             "india_available": True,  "india_note": "500 free images/day; great for beginners"},
    {"name": "NightCafe",         "category": "Image AI",         "maker": "NightCafe",     "pricing": "Free credits daily",             "india_available": True,  "india_note": "Daily free credits; good for hobbyists"},
    {"name": "Clipdrop",          "category": "Image AI",         "maker": "Stability AI",  "pricing": "Free + $14/mo",                  "india_available": True,  "india_note": "Remove backgrounds, clean photos — free tier available"},

    # ── Video Generation ──────────────────────────────────────────────────
    {"name": "Runway ML",         "category": "Video AI",         "maker": "Runway",        "pricing": "Free + from $15/mo",             "india_available": True,  "india_note": "Limited free credits; best for short clips"},
    {"name": "Pika Labs",         "category": "Video AI",         "maker": "Pika",          "pricing": "Free + from $8/mo",              "india_available": True,  "india_note": "Great for social media video generation"},
    {"name": "Kling AI",          "category": "Video AI",         "maker": "Kuaishou",      "pricing": "Free credits available",         "india_available": True,  "india_note": "Strong realistic video; free daily credits"},
    {"name": "HeyGen",            "category": "Video AI",         "maker": "HeyGen",        "pricing": "Free + from $24/mo",             "india_available": True,  "india_note": "Best AI avatar videos; popular for explainers"},
    {"name": "Synthesia",         "category": "Video AI",         "maker": "Synthesia",     "pricing": "From $22/mo",                    "india_available": True,  "india_note": "Enterprise favourite; professional AI avatars"},
    {"name": "Descript",          "category": "Video AI",         "maker": "Descript",      "pricing": "Free + from $24/mo",             "india_available": True,  "india_note": "Best for podcast/video editing with AI transcript"},
    {"name": "Sora",              "category": "Video AI",         "maker": "OpenAI",        "pricing": "Included in ChatGPT Plus",       "india_available": True,  "india_note": "OpenAI's video AI; stunning quality; access via Plus"},
    {"name": "Veo 3",             "category": "Video AI",         "maker": "Google",        "pricing": "Via Google AI Ultra",            "india_available": True,  "india_note": "Google's state-of-art video AI with audio generation"},
    {"name": "Invideo AI",        "category": "Video AI",         "maker": "InVideo",       "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Indian startup; best for YouTube automation"},
    {"name": "Pictory AI",        "category": "Video AI",         "maker": "Pictory",       "pricing": "Free + from $23/mo",             "india_available": True,  "india_note": "Turn blog posts into videos automatically"},
    {"name": "Fliki",             "category": "Video AI",         "maker": "Fliki",         "pricing": "Free + from $21/mo",             "india_available": True,  "india_note": "Text to video + voiceover; good free tier"},
    {"name": "Captions AI",       "category": "Video AI",         "maker": "Captions.ai",   "pricing": "Free + from $10/mo",             "india_available": True,  "india_note": "Auto captions + AI video editing; great for reels"},
    {"name": "CapCut AI",         "category": "Video AI",         "maker": "ByteDance",     "pricing": "Free",                           "india_available": True,  "india_note": "Most popular free video editor in India; AI features"},

    # ── Audio & Voice ─────────────────────────────────────────────────────
    {"name": "ElevenLabs",        "category": "Voice AI",         "maker": "ElevenLabs",    "pricing": "Free + from $5/mo",              "india_available": True,  "india_note": "Best AI voice cloning; has Hindi voices"},
    {"name": "Murf AI",           "category": "Voice AI",         "maker": "Murf",          "pricing": "Free + from $29/mo",             "india_available": True,  "india_note": "Has Indian English and Hindi voices"},
    {"name": "Suno AI",           "category": "Music AI",         "maker": "Suno",          "pricing": "Free + from $10/mo",             "india_available": True,  "india_note": "Generate full songs from text; works in India"},
    {"name": "Udio",              "category": "Music AI",         "maker": "Udio",          "pricing": "Free + from $12/mo",             "india_available": True,  "india_note": "Suno competitor; slightly better music quality"},
    {"name": "Adobe Podcast AI",  "category": "Voice AI",         "maker": "Adobe",         "pricing": "Free in beta",                   "india_available": True,  "india_note": "Free AI audio enhancer; removes background noise instantly"},
    {"name": "Resemble AI",       "category": "Voice AI",         "maker": "Resemble",      "pricing": "Free trial + from $30/mo",       "india_available": True,  "india_note": "Voice cloning with emotional control"},
    {"name": "Play.ht",           "category": "Voice AI",         "maker": "Play.ht",       "pricing": "Free + from $39/mo",             "india_available": True,  "india_note": "Ultra-realistic TTS; Indian English voices available"},
    {"name": "Soundraw",          "category": "Music AI",         "maker": "Soundraw",      "pricing": "From $16.99/mo",                 "india_available": True,  "india_note": "AI music for content creators; royalty-free"},
    {"name": "Boomy",             "category": "Music AI",         "maker": "Boomy",         "pricing": "Free + from $9.99/mo",           "india_available": True,  "india_note": "Create songs in seconds; distribute to Spotify for free"},
    {"name": "Kits AI",           "category": "Voice AI",         "maker": "Kits",          "pricing": "Free + from $9.99/mo",           "india_available": True,  "india_note": "Royalty-free AI voice conversion for music"},

    # ── Coding ────────────────────────────────────────────────────────────
    {"name": "GitHub Copilot",    "category": "Coding AI",        "maker": "GitHub",        "pricing": "Free for students + $10/mo",     "india_available": True,  "india_note": "Free for Indian students with GitHub Education"},
    {"name": "Cursor AI",         "category": "Coding AI",        "maker": "Cursor",        "pricing": "Free + $20/mo Pro",              "india_available": True,  "india_note": "Favourite among Indian developers; VSCode-based"},
    {"name": "Codeium",           "category": "Coding AI",        "maker": "Codeium",       "pricing": "Free forever for individuals",   "india_available": True,  "india_note": "Best free Copilot alternative; works offline"},
    {"name": "Replit AI",         "category": "Coding AI",        "maker": "Replit",        "pricing": "Free + from $25/mo",             "india_available": True,  "india_note": "Best for beginners; code in browser; deploy instantly"},
    {"name": "v0 by Vercel",      "category": "Coding AI",        "maker": "Vercel",        "pricing": "Free + from $10/mo",             "india_available": True,  "india_note": "Generate UI components from text; great for frontend"},
    {"name": "Lovable",           "category": "Coding AI",        "maker": "Lovable",       "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Build full web apps from plain English — no coding needed"},
    {"name": "Windsurf",          "category": "Coding AI",        "maker": "Codeium",       "pricing": "Free + from $15/mo",             "india_available": True,  "india_note": "Agentic AI IDE by Codeium; strong competitor to Cursor"},
    {"name": "Bolt.new",          "category": "Coding AI",        "maker": "StackBlitz",    "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Build and deploy full-stack apps instantly in browser"},
    {"name": "Claude Code",       "category": "Coding AI",        "maker": "Anthropic",     "pricing": "Via Claude Pro/API",             "india_available": True,  "india_note": "Terminal AI coding agent; excellent for complex projects"},
    {"name": "Tabnine",           "category": "Coding AI",        "maker": "Tabnine",       "pricing": "Free + from $12/mo",             "india_available": True,  "india_note": "Privacy-first AI code completion; popular in Indian enterprises"},
    {"name": "Devin AI",          "category": "Coding AI",        "maker": "Cognition",     "pricing": "Enterprise",                     "india_available": True,  "india_note": "World's first AI software engineer; autonomous coding"},
    {"name": "Cline",             "category": "Coding AI",        "maker": "Cline",         "pricing": "Free (open source)",             "india_available": True,  "india_note": "Free open-source AI coding agent for VS Code"},
    {"name": "Continue",          "category": "Coding AI",        "maker": "Continue.dev",  "pricing": "Free (open source)",             "india_available": True,  "india_note": "Free open-source Copilot alternative; use any LLM"},

    # ── Automation & Business ─────────────────────────────────────────────
    {"name": "Zapier AI",         "category": "Automation AI",    "maker": "Zapier",        "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Most popular automation tool; huge Indian user base"},
    {"name": "Make (Integromat)", "category": "Automation AI",    "maker": "Make",          "pricing": "Free + from $9/mo",              "india_available": True,  "india_note": "More powerful than Zapier; better free tier"},
    {"name": "n8n",               "category": "Automation AI",    "maker": "n8n",           "pricing": "Free (self-host) + from $20/mo", "india_available": True,  "india_note": "Open-source Zapier alternative; host on your server free"},
    {"name": "Gamma",             "category": "Presentation AI",  "maker": "Gamma",         "pricing": "Free + from $10/mo",             "india_available": True,  "india_note": "Make presentations/docs from text; beautiful output"},
    {"name": "Beautiful.ai",      "category": "Presentation AI",  "maker": "Beautiful.ai",  "pricing": "From $12/mo",                    "india_available": True,  "india_note": "Smart presentations that auto-design themselves"},
    {"name": "Otter.ai",          "category": "Meeting AI",       "maker": "Otter",         "pricing": "Free + from $17/mo",             "india_available": True,  "india_note": "Best meeting transcription; works with Teams/Meet/Zoom"},
    {"name": "Fireflies.ai",      "category": "Meeting AI",       "maker": "Fireflies",     "pricing": "Free + from $18/mo",             "india_available": True,  "india_note": "Popular in Indian startups for meeting notes"},
    {"name": "Fathom AI",         "category": "Meeting AI",       "maker": "Fathom",        "pricing": "Free + from $19/mo",             "india_available": True,  "india_note": "Free plan is extremely generous; best Zoom notetaker"},
    {"name": "Tldv",              "category": "Meeting AI",       "maker": "Tldv",          "pricing": "Free + from $18/mo",             "india_available": True,  "india_note": "Records and summarises meetings; free tier very usable"},
    {"name": "Clay",              "category": "Automation AI",    "maker": "Clay",          "pricing": "Free + from $149/mo",            "india_available": True,  "india_note": "AI-powered lead enrichment; for B2B sales teams"},

    # ── Search & Research ─────────────────────────────────────────────────
    {"name": "Elicit",            "category": "Research AI",      "maker": "Elicit",        "pricing": "Free + from $12/mo",             "india_available": True,  "india_note": "Best for academic research and literature review"},
    {"name": "Consensus AI",      "category": "Research AI",      "maker": "Consensus",     "pricing": "Free + from $9/mo",              "india_available": True,  "india_note": "Search scientific papers with AI; great for students"},
    {"name": "You.com",           "category": "Search",           "maker": "You.com",       "pricing": "Free + from $15/mo",             "india_available": True,  "india_note": "AI search engine with privacy focus"},
    {"name": "Tavily",            "category": "Search",           "maker": "Tavily",        "pricing": "Free API tier + from $29/mo",    "india_available": True,  "india_note": "AI-optimised search API; great for developers"},
    {"name": "Exa AI",            "category": "Search",           "maker": "Exa",           "pricing": "Free tier + pay per use",        "india_available": True,  "india_note": "Neural search engine; finds the internet by meaning"},

    # ── Indian AI Tools ───────────────────────────────────────────────────
    {"name": "Sarvam AI",         "category": "Indian AI",        "maker": "Sarvam",        "pricing": "API-based pricing",              "india_available": True,  "india_note": "Best Indian LLM; supports 10 Indian languages natively"},
    {"name": "Krutrim",           "category": "Indian AI",        "maker": "Ola",           "pricing": "Free in beta",                   "india_available": True,  "india_note": "India's first unicorn AI startup; made by Ola founder"},
    {"name": "Bhashini",          "category": "Indian AI",        "maker": "Govt of India", "pricing": "Free",                           "india_available": True,  "india_note": "Government AI for Indian language translation — totally free"},
    {"name": "BharatGPT",         "category": "Indian AI",        "maker": "IIT Bombay",    "pricing": "Research access",                "india_available": True,  "india_note": "IIT Bombay-backed; focused on Indian context"},
    {"name": "Zoho Zia",          "category": "Indian AI",        "maker": "Zoho",          "pricing": "Included in Zoho Suite",         "india_available": True,  "india_note": "Indian SaaS giant's AI; integrates with Zoho CRM and more"},
    {"name": "Pepper Content AI", "category": "Indian AI",        "maker": "Pepper Content", "pricing": "Custom pricing",                "india_available": True,  "india_note": "Bengaluru startup; AI-powered content creation platform"},
    {"name": "Haptik",            "category": "Indian AI",        "maker": "Jio",           "pricing": "Enterprise",                     "india_available": True,  "india_note": "India's leading conversational AI; owned by Reliance Jio"},
    {"name": "Framerspace AI",    "category": "Indian AI",        "maker": "Framerspace",   "pricing": "Free beta",                      "india_available": True,  "india_note": "Indian startup building AI creative tools"},

    # ── 3D & Design ──────────────────────────────────────────────────────
    {"name": "Luma AI",           "category": "3D/Video AI",      "maker": "Luma",          "pricing": "Free + from $18/mo",             "india_available": True,  "india_note": "Create 3D scenes and AI video; Dream Machine is impressive"},
    {"name": "Magnific AI",       "category": "Image AI",         "maker": "Magnific",      "pricing": "From $39/mo",                    "india_available": True,  "india_note": "AI image upscaling — makes low-res images HD instantly"},
    {"name": "Locofy AI",         "category": "Coding AI",        "maker": "Locofy",        "pricing": "Free + from $29/mo",             "india_available": True,  "india_note": "Convert Figma designs to React/Next.js code instantly"},
    {"name": "Framer AI",         "category": "Presentation AI",  "maker": "Framer",        "pricing": "Free + from $10/mo",             "india_available": True,  "india_note": "AI website builder; publish full site in minutes"},
    {"name": "Uizard",            "category": "Coding AI",        "maker": "Uizard",        "pricing": "Free + from $12/mo",             "india_available": True,  "india_note": "Sketch to UI mockup in seconds; great for non-designers"},

    # ── Chatbot & Agents ──────────────────────────────────────────────────
    {"name": "Character.ai",      "category": "Chatbot AI",       "maker": "Character.ai",  "pricing": "Free + $9.99/mo Plus",           "india_available": True,  "india_note": "Roleplay and character chatbots — huge in India"},
    {"name": "Poe",               "category": "AI Hub",           "maker": "Quora",         "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Access 20+ AI models in one place; great for comparison"},
    {"name": "Hugging Face",      "category": "AI Platform",      "maker": "HuggingFace",   "pricing": "Free + from $9/mo",              "india_available": True,  "india_note": "GitHub of AI models; free to use thousands of models"},
    {"name": "Replicate",         "category": "AI Platform",      "maker": "Replicate",     "pricing": "Pay per use",                    "india_available": True,  "india_note": "Run any AI model via API; pay only for what you use"},
    {"name": "Tome",              "category": "Presentation AI",  "maker": "Tome",          "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "AI presentation tool with storytelling focus"},
    {"name": "Whisper",           "category": "Transcription AI", "maker": "OpenAI",        "pricing": "Free (open source)",             "india_available": True,  "india_note": "Best free speech-to-text; works for Hindi and Hinglish"},
    {"name": "Claude Projects",   "category": "Productivity",     "maker": "Anthropic",     "pricing": "Included in Claude Pro",         "india_available": True,  "india_note": "Organise AI work by project; remembers context always"},
    {"name": "NotebookLM",        "category": "Research AI",      "maker": "Google",        "pricing": "Free",                           "india_available": True,  "india_note": "Upload any PDF/doc and chat with it — completely free"},
    {"name": "DeepSeek",          "category": "Productivity",     "maker": "DeepSeek",      "pricing": "Free",                           "india_available": True,  "india_note": "Chinese AI — free, powerful, strong at coding and math"},
    {"name": "Grok",              "category": "Productivity",     "maker": "xAI",           "pricing": "Free on X + $16/mo Premium",     "india_available": True,  "india_note": "Elon Musk's AI; real-time X/Twitter data access"},
    {"name": "Napkin AI",         "category": "Visual AI",        "maker": "Napkin",        "pricing": "Free in beta",                   "india_available": True,  "india_note": "Turn text into diagrams and visuals automatically — free"},

    # ── Customer Support & Sales ──────────────────────────────────────────
    {"name": "Intercom AI",       "category": "Automation AI",    "maker": "Intercom",      "pricing": "From $39/mo",                    "india_available": True,  "india_note": "AI customer support bot; adopted widely by Indian SaaS"},
    {"name": "Freshworks AI",     "category": "Automation AI",    "maker": "Freshworks",    "pricing": "Free + from $15/mo",             "india_available": True,  "india_note": "Indian SaaS; AI-powered CRM and support tools"},
    {"name": "Drift AI",          "category": "Automation AI",    "maker": "Drift",         "pricing": "From $2500/yr",                  "india_available": True,  "india_note": "Best AI conversational marketing platform"},
    {"name": "Tidio AI",          "category": "Automation AI",    "maker": "Tidio",         "pricing": "Free + from $29/mo",             "india_available": True,  "india_note": "AI chatbot for e-commerce; great free tier for small biz"},
    {"name": "Gong AI",           "category": "Meeting AI",       "maker": "Gong",          "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI sales coaching; analyses your sales calls for improvements"},

    # ── Data & Analytics ──────────────────────────────────────────────────
    {"name": "Julius AI",         "category": "Research AI",      "maker": "Julius",        "pricing": "Free + from $22/mo",             "india_available": True,  "india_note": "Chat with your Excel/CSV data using AI — no code needed"},
    {"name": "Obviously AI",      "category": "Research AI",      "maker": "Obviously AI",  "pricing": "From $75/mo",                    "india_available": True,  "india_note": "Build prediction models in minutes without coding"},
    {"name": "Rows AI",           "category": "Productivity",     "maker": "Rows",          "pricing": "Free + from $19/mo",             "india_available": True,  "india_note": "AI-powered spreadsheet that understands plain English"},
    {"name": "Akkio",             "category": "Research AI",      "maker": "Akkio",         "pricing": "From $49/mo",                    "india_available": True,  "india_note": "No-code AI forecasting for business data"},

    # ── HR & Recruiting ────────────────────────────────────────────────────
    {"name": "Paradox AI",        "category": "Automation AI",    "maker": "Paradox",       "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI recruiting assistant; used by large Indian corporates"},
    {"name": "Fetcher AI",        "category": "Automation AI",    "maker": "Fetcher",       "pricing": "From $149/mo",                   "india_available": True,  "india_note": "AI that sources and sends recruiting emails automatically"},
    {"name": "Textio",            "category": "Writing",          "maker": "Textio",        "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI writing assistant for inclusive job descriptions"},

    # ── Finance & Legal ───────────────────────────────────────────────────
    {"name": "Harvey AI",         "category": "Productivity",     "maker": "Harvey",        "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI for lawyers; used by top Indian law firms"},
    {"name": "Casetext",          "category": "Research AI",      "maker": "Casetext",      "pricing": "From $65/mo",                    "india_available": True,  "india_note": "AI legal research for Indian lawyers and law students"},
    {"name": "Truewind",          "category": "Automation AI",    "maker": "Truewind",      "pricing": "From $500/mo",                   "india_available": True,  "india_note": "AI-powered accounting automation for startups"},
    {"name": "Vic.ai",            "category": "Automation AI",    "maker": "Vic.ai",        "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI that automates accounts payable for finance teams"},

    # ── Healthcare & Life Sciences ────────────────────────────────────────
    {"name": "Nabla AI",          "category": "Meeting AI",       "maker": "Nabla",         "pricing": "From $99/mo",                    "india_available": True,  "india_note": "AI medical scribe; auto-writes clinical notes for doctors"},
    {"name": "Viz.ai",            "category": "Research AI",      "maker": "Viz.ai",        "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI detects stroke from CT scans in seconds"},
    {"name": "Paige AI",          "category": "Research AI",      "maker": "Paige",         "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI pathology for cancer detection; FDA approved"},

    # ── Education & Learning ──────────────────────────────────────────────
    {"name": "Khanmigo",          "category": "Productivity",     "maker": "Khan Academy",  "pricing": "$9/mo",                          "india_available": True,  "india_note": "Free for teachers in India; best AI tutor for students"},
    {"name": "Duolingo AI",       "category": "Productivity",     "maker": "Duolingo",      "pricing": "Free + $12.99/mo Plus",          "india_available": True,  "india_note": "AI-powered language learning; great for learning English"},
    {"name": "Coursera AI",       "category": "Productivity",     "maker": "Coursera",      "pricing": "Free audit + from $49/mo",       "india_available": True,  "india_note": "AI-guided learning paths on Coursera; discounts for India"},
    {"name": "Quizlet AI",        "category": "Productivity",     "maker": "Quizlet",       "pricing": "Free + $35.99/yr",               "india_available": True,  "india_note": "AI generates flashcards and practice tests from notes"},
    {"name": "Turnitin AI",       "category": "Writing",          "maker": "Turnitin",      "pricing": "Institutional",                  "india_available": True,  "india_note": "Detects AI-written content; used by Indian universities"},

    # ── Marketing & SEO ───────────────────────────────────────────────────
    {"name": "Surfer SEO",        "category": "Writing",          "maker": "Surfer",        "pricing": "From $89/mo",                    "india_available": True,  "india_note": "AI-powered SEO content optimizer; popular for Indian blogs"},
    {"name": "Semrush AI",        "category": "Search",           "maker": "Semrush",       "pricing": "From $129/mo",                   "india_available": True,  "india_note": "AI SEO and content intelligence; free tier available"},
    {"name": "Predis AI",         "category": "Writing",          "maker": "Predis",        "pricing": "Free + from $32/mo",             "india_available": True,  "india_note": "Indian startup; AI generates social media posts from URL"},
    {"name": "Buffer AI",         "category": "Automation AI",    "maker": "Buffer",        "pricing": "Free + from $6/mo",              "india_available": True,  "india_note": "AI social media scheduler; excellent free plan"},
    {"name": "Hootsuite AI",      "category": "Automation AI",    "maker": "Hootsuite",     "pricing": "From $99/mo",                    "india_available": True,  "india_note": "AI content recommendations for social media scheduling"},
    {"name": "Lately AI",         "category": "Writing",          "maker": "Lately",        "pricing": "From $149/mo",                   "india_available": True,  "india_note": "Turns long content into social posts automatically"},
    {"name": "Persado",           "category": "Writing",          "maker": "Persado",       "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI optimizes marketing language for maximum conversion"},

    # ── Misc High-Value ───────────────────────────────────────────────────
    {"name": "Perplexity Pages",  "category": "Research AI",      "maker": "Perplexity",    "pricing": "Included in Perplexity Pro",     "india_available": True,  "india_note": "Create beautiful research reports that auto-update"},
    {"name": "Scribe AI",         "category": "Productivity",     "maker": "Scribe",        "pricing": "Free + from $23/mo",             "india_available": True,  "india_note": "Automatically creates step-by-step guides as you work"},
    {"name": "Loom AI",           "category": "Video AI",         "maker": "Loom",          "pricing": "Free + from $15/mo",             "india_available": True,  "india_note": "Record screen + face; AI summarises and chapters your video"},
    {"name": "Typeface",          "category": "Writing",          "maker": "Typeface",      "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI brand content generation; trained on your brand voice"},
    {"name": "Cohere",            "category": "AI Platform",      "maker": "Cohere",        "pricing": "Free trial + pay per use",       "india_available": True,  "india_note": "Enterprise LLM API; strong for Indian language tasks"},
    {"name": "Mistral AI",        "category": "AI Platform",      "maker": "Mistral",       "pricing": "Free via API + paid plans",      "india_available": True,  "india_note": "Open-source European LLM; faster and cheaper than GPT-4"},
    {"name": "Llama 3",           "category": "AI Platform",      "maker": "Meta",          "pricing": "Free (open source)",             "india_available": True,  "india_note": "Meta's open-source LLM; run locally or via Ollama free"},
    {"name": "Ollama",            "category": "Coding AI",        "maker": "Ollama",        "pricing": "Free (open source)",             "india_available": True,  "india_note": "Run LLMs locally on your laptop; completely free forever"},
    {"name": "LangChain",         "category": "Coding AI",        "maker": "LangChain",     "pricing": "Free (open source)",             "india_available": True,  "india_note": "Build AI agents and apps; most popular AI dev framework"},
    {"name": "Flowise",           "category": "Coding AI",        "maker": "Flowise",       "pricing": "Free (open source)",             "india_available": True,  "india_note": "Build LLM apps visually; drag-and-drop AI workflows — free"},
    {"name": "SuperAGI",          "category": "Automation AI",    "maker": "SuperAGI",      "pricing": "Free (open source)",             "india_available": True,  "india_note": "Indian startup building autonomous AI agents — open source"},
    {"name": "AgentGPT",          "category": "Automation AI",    "maker": "AgentGPT",      "pricing": "Free + from $40/mo",             "india_available": True,  "india_note": "Build and run autonomous AI agents in your browser"},
    {"name": "Semantic Scholar",  "category": "Research AI",      "maker": "Allen AI",      "pricing": "Free",                           "india_available": True,  "india_note": "Best free academic paper search with AI summaries"},
    {"name": "GPT Engineer",      "category": "Coding AI",        "maker": "GPT Engineer",  "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Describe your app in English; AI builds the whole codebase"},
    {"name": "Cody by Sourcegraph","category": "Coding AI",       "maker": "Sourcegraph",   "pricing": "Free + from $9/mo",              "india_available": True,  "india_note": "AI code assistant that understands your entire codebase"},
    {"name": "Warp Terminal",     "category": "Coding AI",        "maker": "Warp",          "pricing": "Free + from $15/mo",             "india_available": True,  "india_note": "AI-powered terminal; explains error messages automatically"},
    {"name": "Aider",             "category": "Coding AI",        "maker": "Aider",         "pricing": "Free (open source)",             "india_available": True,  "india_note": "AI pair programmer in your terminal; works with local models"},
    {"name": "Pieces AI",         "category": "Coding AI",        "maker": "Pieces",        "pricing": "Free",                           "india_available": True,  "india_note": "Save and reuse code snippets with AI context; fully free"},
    {"name": "Glean",             "category": "Search",           "maker": "Glean",         "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI search across all your company tools and documents"},
    {"name": "Dust",              "category": "Productivity",     "maker": "Dust",          "pricing": "From $29/mo per seat",           "india_available": True,  "india_note": "Build AI assistants connected to your company knowledge"},
    {"name": "Mem AI",            "category": "Productivity",     "maker": "Mem",           "pricing": "Free + from $14.99/mo",          "india_available": True,  "india_note": "AI note-taking that auto-organises and surfaces insights"},
    {"name": "Obsidian AI",       "category": "Productivity",     "maker": "Obsidian",      "pricing": "Free + $8/mo Sync",              "india_available": True,  "india_note": "Local-first note-taking with AI plugins; very popular in India"},
    {"name": "Readwise AI",       "category": "Productivity",     "maker": "Readwise",      "pricing": "Free + $7.99/mo",                "india_available": True,  "india_note": "AI summarises articles, books, tweets into daily review"},
    {"name": "Lex AI",            "category": "Writing",          "maker": "Lex",           "pricing": "Free + from $18/mo",             "india_available": True,  "india_note": "AI writing tool for long-form content and essays"},
    {"name": "Rytr",              "category": "Writing",          "maker": "Rytr",          "pricing": "Free + from $9/mo",              "india_available": True,  "india_note": "Affordable AI writer; popular among Indian content creators"},
    {"name": "Hypotenuse AI",     "category": "Writing",          "maker": "Hypotenuse",    "pricing": "From $29/mo",                    "india_available": True,  "india_note": "Best for e-commerce product descriptions at scale"},
    {"name": "Phrasee",           "category": "Writing",          "maker": "Phrasee",       "pricing": "Enterprise",                     "india_available": True,  "india_note": "AI generates subject lines and push notifications that convert"},
    {"name": "Wordtune",          "category": "Writing",          "maker": "AI21 Labs",     "pricing": "Free + from $9.99/mo",           "india_available": True,  "india_note": "Rewrites sentences intelligently; great for non-native English"},
    {"name": "ProWritingAid",     "category": "Writing",          "maker": "ProWritingAid", "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Deep grammar and style analysis; loved by Indian writers"},
    {"name": "Sudowrite",         "category": "Writing",          "maker": "Sudowrite",     "pricing": "From $19/mo",                    "india_available": True,  "india_note": "AI creative writing assistant for fiction and storytelling"},
    {"name": "Novelai",           "category": "Writing",          "maker": "NovelAI",       "pricing": "From $10/mo",                    "india_available": True,  "india_note": "AI storytelling and image generation; privacy-focused"},
    {"name": "Midjourney V6",     "category": "Image AI",         "maker": "Midjourney",    "pricing": "From $10/mo",                    "india_available": True,  "india_note": "Latest Midjourney; photorealistic quality that stuns everyone"},
    {"name": "Krea AI",           "category": "Image AI",         "maker": "Krea",          "pricing": "Free + from $24/mo",             "india_available": True,  "india_note": "Real-time AI image generation and enhancement"},
    {"name": "Scenario AI",       "category": "Image AI",         "maker": "Scenario",      "pricing": "Free + from $24/mo",             "india_available": True,  "india_note": "AI image generation for game developers; great art styles"},
    {"name": "Photoroom AI",      "category": "Image AI",         "maker": "Photoroom",     "pricing": "Free + from $9.99/mo",           "india_available": True,  "india_note": "Remove backgrounds and create product photos with AI"},
    {"name": "Remove.bg",         "category": "Image AI",         "maker": "Kaleido",       "pricing": "Free (5/mo) + $0.09 per image",  "india_available": True,  "india_note": "Remove image backgrounds in one click; widely used in India"},
    {"name": "Vectorize AI",      "category": "Image AI",         "maker": "Vectorize",     "pricing": "Free tier available",            "india_available": True,  "india_note": "Convert raster images to vectors using AI instantly"},
    {"name": "Recraft AI",        "category": "Image AI",         "maker": "Recraft",       "pricing": "Free + from $12/mo",             "india_available": True,  "india_note": "Best AI for vector graphics and brand design"},
    {"name": "Topaz AI",          "category": "Image AI",         "maker": "Topaz Labs",    "pricing": "From $79/yr",                    "india_available": True,  "india_note": "AI photo enhancement; makes blurry images sharp"},
    {"name": "Luminar AI",        "category": "Image AI",         "maker": "Skylum",        "pricing": "From $79",                       "india_available": True,  "india_note": "AI photo editor with sky replacement and portrait tools"},
    {"name": "Remini AI",         "category": "Image AI",         "maker": "Remini",        "pricing": "Free + $9.99/mo",                "india_available": True,  "india_note": "Restore old photos and enhance selfies; very popular in India"},
    {"name": "D-ID",              "category": "Video AI",         "maker": "D-ID",          "pricing": "Free trial + from $25/mo",       "india_available": True,  "india_note": "Turn any photo into a talking AI avatar video"},
    {"name": "Colossyan",         "category": "Video AI",         "maker": "Colossyan",     "pricing": "From $21/mo",                    "india_available": True,  "india_note": "AI video creator with 70+ AI avatars; great for training"},
    {"name": "Elai AI",           "category": "Video AI",         "maker": "Elai",          "pricing": "From $29/mo",                    "india_available": True,  "india_note": "Text to AI avatar video; popular for corporate training"},
    {"name": "Vidyo AI",          "category": "Video AI",         "maker": "Vidyo",         "pricing": "Free + from $29/mo",             "india_available": True,  "india_note": "Indian startup; clips long videos into viral short clips"},
    {"name": "OpusClip",          "category": "Video AI",         "maker": "OpusClip",      "pricing": "Free + from $13/mo",             "india_available": True,  "india_note": "AI finds and clips the viral moments from long videos"},
    {"name": "Munch AI",          "category": "Video AI",         "maker": "Munch",         "pricing": "From $49/mo",                    "india_available": True,  "india_note": "Repurposes long videos into social clips automatically"},
    {"name": "Speechify",         "category": "Voice AI",         "maker": "Speechify",     "pricing": "Free + from $139/yr",            "india_available": True,  "india_note": "Listen to any text at 4.5x speed; great for students"},
    {"name": "NaturalReader",     "category": "Voice AI",         "maker": "NaturalReader", "pricing": "Free + from $9.99/mo",           "india_available": True,  "india_note": "Text-to-speech with natural Indian English voice"},
    {"name": "Voicemaker AI",     "category": "Voice AI",         "maker": "Voicemaker",    "pricing": "Free + from $10/mo",             "india_available": True,  "india_note": "Affordable TTS with Indian English voices; popular in India"},
    {"name": "Krisp AI",          "category": "Voice AI",         "maker": "Krisp",         "pricing": "Free + from $8/mo",              "india_available": True,  "india_note": "Removes background noise from calls in real-time — free plan"},
    {"name": "Cleanvoice AI",     "category": "Voice AI",         "maker": "Cleanvoice",    "pricing": "Free + $10/mo",                  "india_available": True,  "india_note": "Removes filler words and silence from podcasts automatically"},
    {"name": "Podcastle AI",      "category": "Voice AI",         "maker": "Podcastle",     "pricing": "Free + from $23.99/mo",          "india_available": True,  "india_note": "AI-powered podcast recording and editing platform"},
    {"name": "Riverside FM",      "category": "Video AI",         "maker": "Riverside",     "pricing": "Free + from $19/mo",             "india_available": True,  "india_note": "Record studio-quality podcasts/videos remotely; AI editing"},
    {"name": "Wavel AI",          "category": "Voice AI",         "maker": "Wavel",         "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Indian AI dubbing and voice-over platform; 40+ languages"},
    {"name": "Maestra AI",        "category": "Transcription AI", "maker": "Maestra",       "pricing": "Free + from $33/mo",             "india_available": True,  "india_note": "AI transcription with Hindi support; accurate for Indian accents"},
    {"name": "AssemblyAI",        "category": "Transcription AI", "maker": "AssemblyAI",    "pricing": "Free tier + pay per use",        "india_available": True,  "india_note": "Best-in-class transcription API; great for developers"},
    {"name": "Deepgram",          "category": "Transcription AI", "maker": "Deepgram",      "pricing": "Free $200 credit + pay per use", "india_available": True,  "india_note": "Fastest real-time transcription API; great for call centres"},
    {"name": "Gladia",            "category": "Transcription AI", "maker": "Gladia",        "pricing": "Free tier + from $0.0167/min",   "india_available": True,  "india_note": "Real-time transcription API with speaker diarization"},
    {"name": "Zapier Tables",     "category": "Automation AI",    "maker": "Zapier",        "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "AI-powered database that connects to any automation"},
    {"name": "Airtable AI",       "category": "Productivity",     "maker": "Airtable",      "pricing": "Free + from $20/mo/seat",        "india_available": True,  "india_note": "Spreadsheet-database hybrid with AI; very popular in India"},
    {"name": "Coda AI",           "category": "Productivity",     "maker": "Coda",          "pricing": "Free + from $10/mo",             "india_available": True,  "india_note": "Docs + spreadsheet + apps with AI; replaces multiple tools"},
    {"name": "Linear AI",         "category": "Productivity",     "maker": "Linear",        "pricing": "Free + from $8/mo",              "india_available": True,  "india_note": "AI-powered project management; favourite of Indian startups"},
    {"name": "ClickUp AI",        "category": "Productivity",     "maker": "ClickUp",       "pricing": "Free + from $7/mo",              "india_available": True,  "india_note": "All-in-one PM tool with AI writing; Indian army of users"},
    {"name": "Asana AI",          "category": "Productivity",     "maker": "Asana",         "pricing": "Free + from $11/mo",             "india_available": True,  "india_note": "AI project management; popular in Indian agencies"},
    {"name": "Figma AI",          "category": "Image AI",         "maker": "Figma",         "pricing": "Free + from $12/mo",             "india_available": True,  "india_note": "Design tool with AI; most-used by Indian UI/UX designers"},
    {"name": "Sketch AI",         "category": "Image AI",         "maker": "Sketch",        "pricing": "From $12/mo",                    "india_available": True,  "india_note": "Mac design tool with AI features; popular in Indian design firms"},
    {"name": "Pika 2.0",          "category": "Video AI",         "maker": "Pika",          "pricing": "Free + from $8/mo",              "india_available": True,  "india_note": "Latest Pika with cinematic video quality and sound effects"},
    {"name": "MiniMax Video",     "category": "Video AI",         "maker": "MiniMax",       "pricing": "Free tier available",            "india_available": True,  "india_note": "Chinese AI making waves in video generation; free to try"},
    {"name": "Wan AI",            "category": "Video AI",         "maker": "Alibaba",       "pricing": "Free (open source)",             "india_available": True,  "india_note": "Alibaba's open-source video AI; run locally for free"},
    {"name": "Higgsfield AI",     "category": "Video AI",         "maker": "Higgsfield",    "pricing": "Free + from $18/mo",             "india_available": True,  "india_note": "Generate cinematic AI videos with character consistency"},
    {"name": "Google AI Studio",  "category": "AI Platform",      "maker": "Google",        "pricing": "Free",                           "india_available": True,  "india_note": "Build AI apps with Gemini for free; great for developers"},
    {"name": "Vertex AI",         "category": "AI Platform",      "maker": "Google",        "pricing": "Pay per use; free $300 credit",  "india_available": True,  "india_note": "Enterprise-grade AI platform; $300 free credit to start"},
    {"name": "Azure AI",          "category": "AI Platform",      "maker": "Microsoft",     "pricing": "Pay per use; free $200 credit",  "india_available": True,  "india_note": "Microsoft's AI cloud; $200 free credit; integrates with Office"},
    {"name": "AWS Bedrock",       "category": "AI Platform",      "maker": "Amazon",        "pricing": "Pay per use",                    "india_available": True,  "india_note": "Access Claude, Llama, Mistral via AWS; flexible billing"},
    {"name": "Groq",              "category": "AI Platform",      "maker": "Groq",          "pricing": "Free tier + pay per use",        "india_available": True,  "india_note": "Fastest LLM inference in the world; free tier for Llama 3"},
    {"name": "Together AI",       "category": "AI Platform",      "maker": "Together",      "pricing": "Free $25 credit + pay per use",  "india_available": True,  "india_note": "Run open-source models at very low cost; great for developers"},
    {"name": "Weights & Biases",  "category": "AI Platform",      "maker": "W&B",           "pricing": "Free + from $50/mo",             "india_available": True,  "india_note": "Track and visualize ML experiments; used at IIT/IISc"},
    {"name": "DagsHub",           "category": "AI Platform",      "maker": "DagsHub",       "pricing": "Free + from $15/mo",             "india_available": True,  "india_note": "GitHub for data science; built for Indian ML community"},
    {"name": "Label Studio",      "category": "AI Platform",      "maker": "HumanSignal",   "pricing": "Free (open source)",             "india_available": True,  "india_note": "Open-source data labeling for AI training; free to self-host"},
    {"name": "Roboflow",          "category": "AI Platform",      "maker": "Roboflow",      "pricing": "Free + from $249/mo",            "india_available": True,  "india_note": "Build computer vision AI in hours; generous free tier"},
    {"name": "Ultralytics",       "category": "AI Platform",      "maker": "Ultralytics",   "pricing": "Free (open source)",             "india_available": True,  "india_note": "YOLO object detection; most popular CV library among Indian devs"},
    {"name": "Gradio",            "category": "AI Platform",      "maker": "Gradio",        "pricing": "Free (open source)",             "india_available": True,  "india_note": "Build AI demos in Python in minutes; deploy free on Spaces"},
    {"name": "Streamlit",         "category": "AI Platform",      "maker": "Streamlit",     "pricing": "Free + from $20/mo",             "india_available": True,  "india_note": "Build data apps with Python; most popular among Indian data scientists"},
    {"name": "Modal",             "category": "AI Platform",      "maker": "Modal",         "pricing": "Free $30/mo credit + pay per use","india_available": True, "india_note": "Run Python functions in the cloud instantly; great for AI workloads"},
    {"name": "Replika",           "category": "Chatbot AI",       "maker": "Replika",       "pricing": "Free + $9.99/mo Pro",            "india_available": True,  "india_note": "AI companion chatbot; huge user base in India"},
    {"name": "Pi AI",             "category": "Chatbot AI",       "maker": "Inflection",    "pricing": "Free",                           "india_available": True,  "india_note": "Personal AI with empathetic, conversational style"},
    {"name": "Phind",             "category": "Search",           "maker": "Phind",         "pricing": "Free + from $17/mo",             "india_available": True,  "india_note": "AI search engine built for developers; understands code"},
    {"name": "Kagi Search",       "category": "Search",           "maker": "Kagi",          "pricing": "From $5/mo",                     "india_available": True,  "india_note": "Ad-free AI search; no tracking; better signal to noise ratio"},
    {"name": "Brave Leo AI",      "category": "Search",           "maker": "Brave",         "pricing": "Free",                           "india_available": True,  "india_note": "Built-in AI assistant in Brave browser; completely free"},
    {"name": "Arc Browser AI",    "category": "Productivity",     "maker": "The Browser Company","pricing": "Free",                      "india_available": True,  "india_note": "AI-powered browser; summarises pages and answers questions"},
]


def get_short_tool(index: int) -> dict:
    return TOOLS[index % len(TOOLS)]


def get_long_tools(index: int) -> list[dict]:
    start = (index * 5) % len(TOOLS)
    indices = [(start + i) % len(TOOLS) for i in range(5)]
    return [TOOLS[i] for i in indices]
